---
# tasks file for install-jenkins
# roles/example/tasks/main.yml
- name: Install Jenkins on servers
  block:

  - name: Display OS 'os_family'
    debug:
      msg: "Instance is from faimily {{ ansible_facts['os_family']|lower}} "


  - name: Install the correct web server for RHEL
    import_tasks: redhat.yml
    when: ansible_facts['os_family']|lower == 'redhat'

  - name: Install the correct web server for Debian
    import_tasks: debian.yml
    when: ansible_facts['os_family']|lower == 'debian'



  - name: Install Jenkins Server
    package:
      name: "jenkins"
      state: present


  - name: Start jenkins service
    systemd:
      state: started
      name: jenkins
      enabled: yes

  when:  not installasContainer |bool

- name: Install the correct web server for Debian
  import_tasks: docker.yml
  when: installasContainer |bool

- name: Install Git 
  package:
      name: "git"
      state: present
