
- name: Add repository
  yum_repository:
    name: Jenkins
    description: Redhat Jenkins-stable repository
    baseurl: https://pkg.jenkins.io/redhat-stable/
    file: jenkins

- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

# - name: Install Java
#   yum:
#     name: java-11-openjdk
#     state: present
#     update_cache: yes