---
# THIS IS NOT DEBIAN. THIS is actually ubuntu installation.
- name: Remove existing if any
  apt:
    name: 
    - docker 
    - docker-engine 
    - docker.io 
    - containerd 
    - runc


    state: absent


- name: Install docker dependencies
  apt:
    name: 
    - ca-certificates
    - curl
    - gnupg-agent
    - lsb-release

    state: present
    update_cache: yes


- name: Add GPG key for docker debian repo
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add the repo to apt resource list.
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker
    update_cache: yes

- name: Install Docker packages
  apt:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
...