---

  

- name: Install the correct web server for RHEL
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'



- name: Generate an OpenSSH keypair dockeradmin
  community.crypto.openssh_keypair:
    path: ~/.ssh/dockeradmin.pem
  delegate_to: 127.0.0.1
  become: false

- name: Add a dockeradmin user
  ansible.builtin.user:
    name: dockeradmin
    comment: Docker Admin user
    group: docker
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Set authorized key for user ubuntu copying it from current user
  ansible.posix.authorized_key:
    user: dockeradmin
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/dockeradmin.pem.pub') }}"