---
# tasks file for get-ec2-details
- name: Display all existing instances
  amazon.aws.ec2_instance_info:
      filters:
        
        instance-state-name: [ "running"]
  register: ec2_instances_list

- name: Print Details
  debug:
    msg:
      - "Instance ID - {{item.instance_id }}"
      - "Private DNS - {{item.private_dns_name }}"
      - "Private IP - {{item.private_ip_address}}"
      - "Public IP - {{item.public_ip_address }}"
      - "Public DNS - {{item.public_dns_name }}"
      - "Tags DNS - {{item.tags }}"
  loop: "{{ec2_instances_list.instances}}"
  ignore_errors: true