- hosts:  AWS-EC2

  name: Play to install Jenkins WebServer
  vars:
    ansible_ssh_private_key_file: /home/avinash/.ssh/my-key-pair.pem
    ansible_user: ec2-user
  roles:
    - name: Install Jenkins
      role: install-jenkins
      become: yes