---
# ansible-playbook setup-docker.yml -e serverName=3.110.157.95 -i 3.110.157.95,

- hosts: "{{serverName}}"
  name: Play to install Docker
  become: yes
  vars:
    ansible_ssh_private_key_file: /home/avinash/.ssh/my-key-pair.pem
    ansible_user: ubuntu
    installasContainer: true
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - name: Install Docker
      role: install-docker
      tags: docker
    - name: Install Jenkins
      role: install-jenkins
      tags: jenkins
